- name: Configuración del fichero /etc/network/interfaces
  ansible.builtin.template:
    src: etc/network/interfaces
    dest: /etc/network/interfaces
    owner: root
    group: root
    mode: '0640'
  notify:
    - reinicio del sistema

